### ISSUE TITLE
Newsletter-email input box render : thingsWorthDoing

### ISSUE THREAD

**Issue by manaspz** [hoppersroppers/library#2]
- Is there a reason to have these two in place or are they redundant ?

<img width="818" alt="ss" src="https://github.com/hoppersroppers/library/assets/62481581/afb309e3-41b4-48d6-8d40-b1a51e290594">

**Comment by deveyNull** [comment]
Completely by accident. Had some sort of scripted logic to put these on and must have broken it.

**Comment by manaspz** [comment]
Will leave it at that, not fixing it ! 
It's broken because of jekyll build.
